from typing import List, Optional

class TurkeyMap:
    def __init__(self) -> None: ...
    def insert(
        self,
        ent_id: int,
        prop_name: str,
        prop: bytes,
    ) -> None: ...
    def get_by_id(self, ent_id: int) -> List[bytes]: ...
    def get_by_prop(self, prop_name: str) -> List[bytes]: ...
    def get(self, ent_id: int, prop_name: str) -> Optional[bytes]: ...
    def update(self, ent_id: int, prop_name: str, prop: bytes) -> None: ...
